backend_args = None
batch_size = 4
branch_field = [
    'sup',
    'unsup_teacher',
    'unsup_student',
]
color_space = [
    [
        dict(type='ColorTransform'),
    ],
    [
        dict(type='AutoContrast'),
    ],
    [
        dict(type='Equalize'),
    ],
    [
        dict(type='Sharpness'),
    ],
    [
        dict(type='Posterize'),
    ],
    [
        dict(type='Solarize'),
    ],
    [
        dict(type='Color'),
    ],
    [
        dict(type='Contrast'),
    ],
    [
        dict(type='Brightness'),
    ],
]
custom_hooks = [
    dict(type='MeanTeacherHook'),
]
data_root = '/home/luodi23/mmdetection/data/split_data/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        by_epoch=False, interval=1000, max_keep_ckpts=2,
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='DetVisualizationHook'))
default_scope = 'mmdet'
detector = dict(
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(
            checkpoint='open-mmlab://detectron2/resnet50_caffe',
            type='Pretrained'),
        norm_cfg=dict(requires_grad=False, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='caffe',
        type='ResNet'),
    data_preprocessor=dict(
        bgr_to_rgb=False,
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        pad_size_divisor=32,
        std=[
            1.0,
            1.0,
            1.0,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=5,
        out_channels=256,
        type='FPN'),
    roi_head=dict(
        bbox_head=dict(
            bbox_coder=dict(
                target_means=[
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                target_stds=[
                    0.1,
                    0.1,
                    0.2,
                    0.2,
                ],
                type='DeltaXYWHBBoxCoder'),
            fc_out_channels=1024,
            in_channels=256,
            loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
            loss_cls=dict(
                loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=False),
            num_classes=2,
            reg_class_agnostic=False,
            roi_feat_size=7,
            type='Shared2FCBBoxHead'),
        bbox_roi_extractor=dict(
            featmap_strides=[
                4,
                8,
                16,
                32,
            ],
            out_channels=256,
            roi_layer=dict(output_size=7, sampling_ratio=0, type='RoIAlign'),
            type='SingleRoIExtractor'),
        type='StandardRoIHead'),
    rpn_head=dict(
        anchor_generator=dict(
            ratios=[
                0.5,
                1.0,
                2.0,
            ],
            scales=[
                8,
            ],
            strides=[
                4,
                8,
                16,
                32,
                64,
            ],
            type='AnchorGenerator'),
        bbox_coder=dict(
            target_means=[
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            target_stds=[
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            type='DeltaXYWHBBoxCoder'),
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
        loss_cls=dict(
            loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=True),
        type='RPNHead'),
    test_cfg=dict(
        rcnn=dict(
            max_per_img=300,
            nms=dict(iou_threshold=0.5, min_score=0.001, type='soft_nms'),
            score_thr=0.01),
        rpn=dict(
            max_per_img=1000,
            min_bbox_size=0,
            nms=dict(iou_threshold=0.7, type='nms'),
            nms_pre=2000)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=False,
                min_pos_iou=0.5,
                neg_iou_thr=0.5,
                pos_iou_thr=0.5,
                type='MaxIoUAssigner'),
            debug=False,
            pos_weight=-1,
            sampler=dict(
                add_gt_as_proposals=True,
                neg_pos_ub=-1,
                num=512,
                pos_fraction=0.25,
                type='RandomSampler')),
        rpn=dict(
            allowed_border=-1,
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=True,
                min_pos_iou=0.3,
                neg_iou_thr=0.3,
                pos_iou_thr=0.7,
                type='MaxIoUAssigner'),
            debug=False,
            pos_weight=-1,
            sampler=dict(
                add_gt_as_proposals=False,
                neg_pos_ub=-1,
                num=512,
                pos_fraction=0.5,
                type='RandomSampler')),
        rpn_proposal=dict(
            max_per_img=1000,
            min_bbox_size=0,
            nms=dict(iou_threshold=0.7, type='nms'),
            nms_pre=2000)),
    type='FasterRCNN')
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
geometric = [
    [
        dict(type='Rotate'),
    ],
    [
        dict(type='ShearX'),
    ],
    [
        dict(type='ShearY'),
    ],
    [
        dict(type='TranslateX'),
    ],
    [
        dict(type='TranslateY'),
    ],
]
labeled_dataset = dict(
    ann_file='annotations/train/labeled/coco_detection.json',
    backend_args=None,
    data_prefix=dict(img='train/labeled/'),
    data_root='/home/luodi23/mmdetection/data/split_data/',
    filter_cfg=dict(filter_empty_gt=True, min_size=32),
    metainfo=dict(
        classes=(
            'germinated',
            'ungerminated',
        ),
        palette=[
            (
                212,
                212,
                255,
            ),
            (
                255,
                212,
                212,
            ),
        ]),
    pipeline=[
        dict(backend_args=None, type='LoadImageFromFile'),
        dict(type='LoadAnnotations', with_bbox=True),
        dict(
            keep_ratio=True,
            scale=[
                (
                    1600,
                    800,
                ),
                (
                    2000,
                    1000,
                ),
            ],
            type='RandomResize'),
        dict(prob=0.5, type='RandomFlip'),
        dict(
            aug_num=1,
            aug_space=[
                [
                    dict(type='ColorTransform'),
                ],
                [
                    dict(type='AutoContrast'),
                ],
                [
                    dict(type='Equalize'),
                ],
                [
                    dict(type='Sharpness'),
                ],
                [
                    dict(type='Posterize'),
                ],
                [
                    dict(type='Solarize'),
                ],
                [
                    dict(type='Color'),
                ],
                [
                    dict(type='Contrast'),
                ],
                [
                    dict(type='Brightness'),
                ],
            ],
            type='RandAugment'),
        dict(min_gt_bbox_wh=(
            0.01,
            0.01,
        ), type='FilterAnnotations'),
        dict(
            branch_field=[
                'sup',
                'unsup_teacher',
                'unsup_student',
            ],
            sup=dict(type='PackDetInputs'),
            type='MultiBranch'),
    ],
    type='CocoDataset')
launcher = 'none'
load_from = '/home/luodi23/mmdetection/work_dirs/soft-teacher_faster-rcnn_r50-caffe_fpn_18k_semi-0.1-seedlingdetection/iter_4000.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=False, type='LogProcessor', window_size=50)
metainfo = dict(
    classes=(
        'germinated',
        'ungerminated',
    ),
    palette=[
        (
            212,
            212,
            255,
        ),
        (
            255,
            212,
            212,
        ),
    ])
model = dict(
    data_preprocessor=dict(
        data_preprocessor=dict(
            bgr_to_rgb=False,
            mean=[
                103.53,
                116.28,
                123.675,
            ],
            pad_size_divisor=32,
            std=[
                1.0,
                1.0,
                1.0,
            ],
            type='DetDataPreprocessor'),
        type='MultiBranchDataPreprocessor'),
    detector=dict(
        backbone=dict(
            depth=50,
            frozen_stages=1,
            init_cfg=dict(
                checkpoint='open-mmlab://detectron2/resnet50_caffe',
                type='Pretrained'),
            norm_cfg=dict(requires_grad=False, type='BN'),
            norm_eval=True,
            num_stages=4,
            out_indices=(
                0,
                1,
                2,
                3,
            ),
            style='caffe',
            type='ResNet'),
        data_preprocessor=dict(
            bgr_to_rgb=False,
            mean=[
                103.53,
                116.28,
                123.675,
            ],
            pad_size_divisor=32,
            std=[
                1.0,
                1.0,
                1.0,
            ],
            type='DetDataPreprocessor'),
        neck=dict(
            in_channels=[
                256,
                512,
                1024,
                2048,
            ],
            num_outs=5,
            out_channels=256,
            type='FPN'),
        roi_head=dict(
            bbox_head=dict(
                bbox_coder=dict(
                    target_means=[
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                    target_stds=[
                        0.1,
                        0.1,
                        0.2,
                        0.2,
                    ],
                    type='DeltaXYWHBBoxCoder'),
                fc_out_channels=1024,
                in_channels=256,
                loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
                loss_cls=dict(
                    loss_weight=1.0,
                    type='CrossEntropyLoss',
                    use_sigmoid=False),
                num_classes=2,
                reg_class_agnostic=False,
                roi_feat_size=7,
                type='Shared2FCBBoxHead'),
            bbox_roi_extractor=dict(
                featmap_strides=[
                    4,
                    8,
                    16,
                    32,
                ],
                out_channels=256,
                roi_layer=dict(
                    output_size=7, sampling_ratio=0, type='RoIAlign'),
                type='SingleRoIExtractor'),
            type='StandardRoIHead'),
        rpn_head=dict(
            anchor_generator=dict(
                ratios=[
                    0.5,
                    1.0,
                    2.0,
                ],
                scales=[
                    8,
                ],
                strides=[
                    4,
                    8,
                    16,
                    32,
                    64,
                ],
                type='AnchorGenerator'),
            bbox_coder=dict(
                target_means=[
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                target_stds=[
                    1.0,
                    1.0,
                    1.0,
                    1.0,
                ],
                type='DeltaXYWHBBoxCoder'),
            feat_channels=256,
            in_channels=256,
            loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
            loss_cls=dict(
                loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=True),
            type='RPNHead'),
        test_cfg=dict(
            rcnn=dict(
                max_per_img=300,
                nms=dict(iou_threshold=0.5, min_score=0.001, type='soft_nms'),
                score_thr=0.01),
            rpn=dict(
                max_per_img=1000,
                min_bbox_size=0,
                nms=dict(iou_threshold=0.7, type='nms'),
                nms_pre=2000)),
        train_cfg=dict(
            rcnn=dict(
                assigner=dict(
                    ignore_iof_thr=-1,
                    match_low_quality=False,
                    min_pos_iou=0.5,
                    neg_iou_thr=0.5,
                    pos_iou_thr=0.5,
                    type='MaxIoUAssigner'),
                debug=False,
                pos_weight=-1,
                sampler=dict(
                    add_gt_as_proposals=True,
                    neg_pos_ub=-1,
                    num=512,
                    pos_fraction=0.25,
                    type='RandomSampler')),
            rpn=dict(
                allowed_border=-1,
                assigner=dict(
                    ignore_iof_thr=-1,
                    match_low_quality=True,
                    min_pos_iou=0.3,
                    neg_iou_thr=0.3,
                    pos_iou_thr=0.7,
                    type='MaxIoUAssigner'),
                debug=False,
                pos_weight=-1,
                sampler=dict(
                    add_gt_as_proposals=False,
                    neg_pos_ub=-1,
                    num=512,
                    pos_fraction=0.5,
                    type='RandomSampler')),
            rpn_proposal=dict(
                max_per_img=1000,
                min_bbox_size=0,
                nms=dict(iou_threshold=0.7, type='nms'),
                nms_pre=2000)),
        type='FasterRCNN'),
    semi_test_cfg=dict(predict_on='teacher'),
    semi_train_cfg=dict(
        cls_pseudo_thr=0.9,
        freeze_teacher=True,
        jitter_scale=0.06,
        jitter_times=10,
        min_pseudo_bbox_wh=(
            0.01,
            0.01,
        ),
        pseudo_label_initial_score_thr=0.5,
        reg_pseudo_thr=0.02,
        rpn_pseudo_thr=0.9,
        sup_weight=1.0,
        unsup_weight=3.0),
    type='SoftTeacher')
num_workers = 5
optim_wrapper = dict(
    optimizer=dict(lr=0.0002, type='AdamW', weight_decay=0.0001),
    type='OptimWrapper')
param_scheduler = [
    dict(begin=0, by_epoch=False, end=50, start_factor=0.001, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=False,
        end=18000,
        gamma=0.1,
        milestones=[
            12000,
            16000,
        ],
        type='MultiStepLR'),
]
resume = False
scale = [
    (
        1600,
        800,
    ),
    (
        2000,
        1000,
    ),
]
strong_pipeline = [
    dict(
        keep_ratio=True,
        scale=[
            (
                1600,
                800,
            ),
            (
                2000,
                1000,
            ),
        ],
        type='RandomResize'),
    dict(prob=0.5, type='RandomFlip'),
    dict(
        transforms=[
            dict(
                aug_num=1,
                aug_space=[
                    [
                        dict(type='ColorTransform'),
                    ],
                    [
                        dict(type='AutoContrast'),
                    ],
                    [
                        dict(type='Equalize'),
                    ],
                    [
                        dict(type='Sharpness'),
                    ],
                    [
                        dict(type='Posterize'),
                    ],
                    [
                        dict(type='Solarize'),
                    ],
                    [
                        dict(type='Color'),
                    ],
                    [
                        dict(type='Contrast'),
                    ],
                    [
                        dict(type='Brightness'),
                    ],
                ],
                type='RandAugment'),
            dict(
                aug_num=1,
                aug_space=[
                    [
                        dict(type='Rotate'),
                    ],
                    [
                        dict(type='ShearX'),
                    ],
                    [
                        dict(type='ShearY'),
                    ],
                    [
                        dict(type='TranslateX'),
                    ],
                    [
                        dict(type='TranslateY'),
                    ],
                ],
                type='RandAugment'),
        ],
        type='RandomOrder'),
    dict(n_patches=(
        1,
        5,
    ), ratio=(
        0,
        0.2,
    ), type='RandomErasing'),
    dict(min_gt_bbox_wh=(
        0.01,
        0.01,
    ), type='FilterAnnotations'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'flip',
            'flip_direction',
            'homography_matrix',
        ),
        type='PackDetInputs'),
]
sup_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        keep_ratio=True,
        scale=[
            (
                1600,
                800,
            ),
            (
                2000,
                1000,
            ),
        ],
        type='RandomResize'),
    dict(prob=0.5, type='RandomFlip'),
    dict(
        aug_num=1,
        aug_space=[
            [
                dict(type='ColorTransform'),
            ],
            [
                dict(type='AutoContrast'),
            ],
            [
                dict(type='Equalize'),
            ],
            [
                dict(type='Sharpness'),
            ],
            [
                dict(type='Posterize'),
            ],
            [
                dict(type='Solarize'),
            ],
            [
                dict(type='Color'),
            ],
            [
                dict(type='Contrast'),
            ],
            [
                dict(type='Brightness'),
            ],
        ],
        type='RandAugment'),
    dict(min_gt_bbox_wh=(
        0.01,
        0.01,
    ), type='FilterAnnotations'),
    dict(
        branch_field=[
            'sup',
            'unsup_teacher',
            'unsup_student',
        ],
        sup=dict(type='PackDetInputs'),
        type='MultiBranch'),
]
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/val/coco_detection.json',
        backend_args=None,
        data_prefix=dict(img='val/'),
        data_root='/home/luodi23/mmdetection/data/split_data/',
        metainfo=dict(
            classes=(
                'germinated',
                'ungerminated',
            ),
            palette=[
                (
                    212,
                    212,
                    255,
                ),
                (
                    255,
                    212,
                    212,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1600,
                800,
            ), type='Resize'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file=
    '/home/luodi23/mmdetection/data/split_data/annotations/val/coco_detection.json',
    backend_args=None,
    format_only=False,
    metric='bbox',
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        1600,
        800,
    ), type='Resize'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(max_iters=18000, type='IterBasedTrainLoop', val_interval=1000)
train_dataloader = dict(
    batch_size=4,
    dataset=dict(
        datasets=[
            dict(
                ann_file='annotations/train/labeled/coco_detection.json',
                backend_args=None,
                data_prefix=dict(img='train/labeled/'),
                data_root='/home/luodi23/mmdetection/data/split_data/',
                filter_cfg=dict(filter_empty_gt=True, min_size=32),
                metainfo=dict(
                    classes=(
                        'germinated',
                        'ungerminated',
                    ),
                    palette=[
                        (
                            212,
                            212,
                            255,
                        ),
                        (
                            255,
                            212,
                            212,
                        ),
                    ]),
                pipeline=[
                    dict(backend_args=None, type='LoadImageFromFile'),
                    dict(type='LoadAnnotations', with_bbox=True),
                    dict(
                        keep_ratio=True,
                        scale=[
                            (
                                1600,
                                800,
                            ),
                            (
                                2000,
                                1000,
                            ),
                        ],
                        type='RandomResize'),
                    dict(prob=0.5, type='RandomFlip'),
                    dict(
                        aug_num=1,
                        aug_space=[
                            [
                                dict(type='ColorTransform'),
                            ],
                            [
                                dict(type='AutoContrast'),
                            ],
                            [
                                dict(type='Equalize'),
                            ],
                            [
                                dict(type='Sharpness'),
                            ],
                            [
                                dict(type='Posterize'),
                            ],
                            [
                                dict(type='Solarize'),
                            ],
                            [
                                dict(type='Color'),
                            ],
                            [
                                dict(type='Contrast'),
                            ],
                            [
                                dict(type='Brightness'),
                            ],
                        ],
                        type='RandAugment'),
                    dict(
                        min_gt_bbox_wh=(
                            0.01,
                            0.01,
                        ),
                        type='FilterAnnotations'),
                    dict(
                        branch_field=[
                            'sup',
                            'unsup_teacher',
                            'unsup_student',
                        ],
                        sup=dict(type='PackDetInputs'),
                        type='MultiBranch'),
                ],
                type='CocoDataset'),
            dict(
                ann_file='annotations/train/unlabeled/coco_detection.json',
                backend_args=None,
                data_prefix=dict(img='train/unlabeled/'),
                data_root='/home/luodi23/mmdetection/data/split_data/',
                filter_cfg=dict(filter_empty_gt=False),
                pipeline=[
                    dict(backend_args=None, type='LoadImageFromFile'),
                    dict(type='LoadEmptyAnnotations'),
                    dict(
                        branch_field=[
                            'sup',
                            'unsup_teacher',
                            'unsup_student',
                        ],
                        type='MultiBranch',
                        unsup_student=[
                            dict(
                                keep_ratio=True,
                                scale=[
                                    (
                                        1600,
                                        800,
                                    ),
                                    (
                                        2000,
                                        1000,
                                    ),
                                ],
                                type='RandomResize'),
                            dict(prob=0.5, type='RandomFlip'),
                            dict(
                                transforms=[
                                    dict(
                                        aug_num=1,
                                        aug_space=[
                                            [
                                                dict(type='ColorTransform'),
                                            ],
                                            [
                                                dict(type='AutoContrast'),
                                            ],
                                            [
                                                dict(type='Equalize'),
                                            ],
                                            [
                                                dict(type='Sharpness'),
                                            ],
                                            [
                                                dict(type='Posterize'),
                                            ],
                                            [
                                                dict(type='Solarize'),
                                            ],
                                            [
                                                dict(type='Color'),
                                            ],
                                            [
                                                dict(type='Contrast'),
                                            ],
                                            [
                                                dict(type='Brightness'),
                                            ],
                                        ],
                                        type='RandAugment'),
                                    dict(
                                        aug_num=1,
                                        aug_space=[
                                            [
                                                dict(type='Rotate'),
                                            ],
                                            [
                                                dict(type='ShearX'),
                                            ],
                                            [
                                                dict(type='ShearY'),
                                            ],
                                            [
                                                dict(type='TranslateX'),
                                            ],
                                            [
                                                dict(type='TranslateY'),
                                            ],
                                        ],
                                        type='RandAugment'),
                                ],
                                type='RandomOrder'),
                            dict(
                                n_patches=(
                                    1,
                                    5,
                                ),
                                ratio=(
                                    0,
                                    0.2,
                                ),
                                type='RandomErasing'),
                            dict(
                                min_gt_bbox_wh=(
                                    0.01,
                                    0.01,
                                ),
                                type='FilterAnnotations'),
                            dict(
                                meta_keys=(
                                    'img_id',
                                    'img_path',
                                    'ori_shape',
                                    'img_shape',
                                    'scale_factor',
                                    'flip',
                                    'flip_direction',
                                    'homography_matrix',
                                ),
                                type='PackDetInputs'),
                        ],
                        unsup_teacher=[
                            dict(
                                keep_ratio=True,
                                scale=[
                                    (
                                        1600,
                                        800,
                                    ),
                                    (
                                        2000,
                                        1000,
                                    ),
                                ],
                                type='RandomResize'),
                            dict(prob=0.5, type='RandomFlip'),
                            dict(
                                meta_keys=(
                                    'img_id',
                                    'img_path',
                                    'ori_shape',
                                    'img_shape',
                                    'scale_factor',
                                    'flip',
                                    'flip_direction',
                                    'homography_matrix',
                                ),
                                type='PackDetInputs'),
                        ]),
                ],
                type='CocoDataset'),
        ],
        type='ConcatDataset'),
    num_workers=5,
    persistent_workers=True,
    sampler=dict(
        batch_size=4, source_ratio=[
            1,
            3,
        ], type='GroupMultiSourceSampler'))
unlabeled_dataset = dict(
    ann_file='annotations/train/unlabeled/coco_detection.json',
    backend_args=None,
    data_prefix=dict(img='train/unlabeled/'),
    data_root='/home/luodi23/mmdetection/data/split_data/',
    filter_cfg=dict(filter_empty_gt=False),
    pipeline=[
        dict(backend_args=None, type='LoadImageFromFile'),
        dict(type='LoadEmptyAnnotations'),
        dict(
            branch_field=[
                'sup',
                'unsup_teacher',
                'unsup_student',
            ],
            type='MultiBranch',
            unsup_student=[
                dict(
                    keep_ratio=True,
                    scale=[
                        (
                            1600,
                            800,
                        ),
                        (
                            2000,
                            1000,
                        ),
                    ],
                    type='RandomResize'),
                dict(prob=0.5, type='RandomFlip'),
                dict(
                    transforms=[
                        dict(
                            aug_num=1,
                            aug_space=[
                                [
                                    dict(type='ColorTransform'),
                                ],
                                [
                                    dict(type='AutoContrast'),
                                ],
                                [
                                    dict(type='Equalize'),
                                ],
                                [
                                    dict(type='Sharpness'),
                                ],
                                [
                                    dict(type='Posterize'),
                                ],
                                [
                                    dict(type='Solarize'),
                                ],
                                [
                                    dict(type='Color'),
                                ],
                                [
                                    dict(type='Contrast'),
                                ],
                                [
                                    dict(type='Brightness'),
                                ],
                            ],
                            type='RandAugment'),
                        dict(
                            aug_num=1,
                            aug_space=[
                                [
                                    dict(type='Rotate'),
                                ],
                                [
                                    dict(type='ShearX'),
                                ],
                                [
                                    dict(type='ShearY'),
                                ],
                                [
                                    dict(type='TranslateX'),
                                ],
                                [
                                    dict(type='TranslateY'),
                                ],
                            ],
                            type='RandAugment'),
                    ],
                    type='RandomOrder'),
                dict(
                    n_patches=(
                        1,
                        5,
                    ), ratio=(
                        0,
                        0.2,
                    ), type='RandomErasing'),
                dict(min_gt_bbox_wh=(
                    0.01,
                    0.01,
                ), type='FilterAnnotations'),
                dict(
                    meta_keys=(
                        'img_id',
                        'img_path',
                        'ori_shape',
                        'img_shape',
                        'scale_factor',
                        'flip',
                        'flip_direction',
                        'homography_matrix',
                    ),
                    type='PackDetInputs'),
            ],
            unsup_teacher=[
                dict(
                    keep_ratio=True,
                    scale=[
                        (
                            1600,
                            800,
                        ),
                        (
                            2000,
                            1000,
                        ),
                    ],
                    type='RandomResize'),
                dict(prob=0.5, type='RandomFlip'),
                dict(
                    meta_keys=(
                        'img_id',
                        'img_path',
                        'ori_shape',
                        'img_shape',
                        'scale_factor',
                        'flip',
                        'flip_direction',
                        'homography_matrix',
                    ),
                    type='PackDetInputs'),
            ]),
    ],
    type='CocoDataset')
unsup_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadEmptyAnnotations'),
    dict(
        branch_field=[
            'sup',
            'unsup_teacher',
            'unsup_student',
        ],
        type='MultiBranch',
        unsup_student=[
            dict(
                keep_ratio=True,
                scale=[
                    (
                        1600,
                        800,
                    ),
                    (
                        2000,
                        1000,
                    ),
                ],
                type='RandomResize'),
            dict(prob=0.5, type='RandomFlip'),
            dict(
                transforms=[
                    dict(
                        aug_num=1,
                        aug_space=[
                            [
                                dict(type='ColorTransform'),
                            ],
                            [
                                dict(type='AutoContrast'),
                            ],
                            [
                                dict(type='Equalize'),
                            ],
                            [
                                dict(type='Sharpness'),
                            ],
                            [
                                dict(type='Posterize'),
                            ],
                            [
                                dict(type='Solarize'),
                            ],
                            [
                                dict(type='Color'),
                            ],
                            [
                                dict(type='Contrast'),
                            ],
                            [
                                dict(type='Brightness'),
                            ],
                        ],
                        type='RandAugment'),
                    dict(
                        aug_num=1,
                        aug_space=[
                            [
                                dict(type='Rotate'),
                            ],
                            [
                                dict(type='ShearX'),
                            ],
                            [
                                dict(type='ShearY'),
                            ],
                            [
                                dict(type='TranslateX'),
                            ],
                            [
                                dict(type='TranslateY'),
                            ],
                        ],
                        type='RandAugment'),
                ],
                type='RandomOrder'),
            dict(n_patches=(
                1,
                5,
            ), ratio=(
                0,
                0.2,
            ), type='RandomErasing'),
            dict(min_gt_bbox_wh=(
                0.01,
                0.01,
            ), type='FilterAnnotations'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'flip',
                    'flip_direction',
                    'homography_matrix',
                ),
                type='PackDetInputs'),
        ],
        unsup_teacher=[
            dict(
                keep_ratio=True,
                scale=[
                    (
                        1600,
                        800,
                    ),
                    (
                        2000,
                        1000,
                    ),
                ],
                type='RandomResize'),
            dict(prob=0.5, type='RandomFlip'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'flip',
                    'flip_direction',
                    'homography_matrix',
                ),
                type='PackDetInputs'),
        ]),
]
val_cfg = dict(type='TeacherStudentValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/val/coco_detection.json',
        backend_args=None,
        data_prefix=dict(img='val/'),
        data_root='/home/luodi23/mmdetection/data/split_data/',
        metainfo=dict(
            classes=(
                'germinated',
                'ungerminated',
            ),
            palette=[
                (
                    212,
                    212,
                    255,
                ),
                (
                    255,
                    212,
                    212,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1600,
                800,
            ), type='Resize'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file=
    '/home/luodi23/mmdetection/data/split_data/annotations/val/coco_detection.json',
    backend_args=None,
    format_only=False,
    metric='bbox',
    type='CocoMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(type='TensorboardVisBackend'),
    ])
weak_pipeline = [
    dict(
        keep_ratio=True,
        scale=[
            (
                1600,
                800,
            ),
            (
                2000,
                1000,
            ),
        ],
        type='RandomResize'),
    dict(prob=0.5, type='RandomFlip'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'flip',
            'flip_direction',
            'homography_matrix',
        ),
        type='PackDetInputs'),
]
work_dir = './work_dirs/soft-teacher_faster-rcnn_r50-caffe_fpn_18k_semi-0.1-seedlingdetection'
